logging:
  ##设置日志路径和日志文件名
  file: /var/logs/TacoCloud.log
  ##设置日志级别
  level:
    root: WARN
    org.springframework.security: DEBUG

##设置页面大小
taco:
  orders:
    pageSize : 10
##设置基础访问路径
spring:
  data:
    rest:
      base-path: /api
##设置jms，设置代理ActiveMQ
  activemq:
    broker-url: tcp://activemq.tacocloud.com
    user: tacoweb
    password: 13tm31n
##设置消息发送的默认目的地
  jms:
    template:
      default-destination: tacocloud.order.queue

---
##设置一个profiles名为prod
##激活profiles
spring:
  profiles:
    active:
      - prod

  dataSource:
    url : jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN